table notepd
	lineageTag: 9bee8963-4deb-47c7-8e21-e9360b5d82d0

	column id
		dataType: int64
		formatString: 0
		lineageTag: afd9e56e-defc-4624-a9b5-432b8f51ffde
		summarizeBy: sum
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: decb04ad-4087-439c-9e18-ad13cc2512b7
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	partition notepd = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Zidio project\archive\notepd.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

